files:
  include: '**/*.s+(a|c)ss'
  ignore:
rules:
  # Consistency rules
  border-zero:
    - 1
    - convention: zero
  class-name-format:
    - 1
    - convention: hyphenatedlowercase
  clean-import-paths:
    - 1
    - filename-extension: false
      leading-underscore: false
  no-extends: 1
  extends-before-mixins: 1
  extends-before-declarations: 1
  force-element-nesting: 1
  force-pseudo-nesting: 1
  mixins-before-declarations:
    - 2
    - 
      exclude:
        - mobile
        - tablet
        - desktop
        - breakpoint
  empty-line-between-blocks: 1
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-important: 1
  no-invalid-hex: 1
  no-transition-all: 0
  no-vendor-prefixes:
    - 1
  final-newline: 0
  no-ids: 1
  leading-zero:
    - 1
    - include: true
  name-format: 0
  nesting-depth:
    - 1
    - max-depth: 1
  placeholder-in-extend: 1
  property-sort-order:
    - 1
    # - ignore-custom-properties: false
    - order: smacss
  property-spelling: 0
  shorthand: 0
  one-declaration-per-line: 1
  single-line-per-selector: 0
  space-after-bang:
    - 1
    - include: false
  space-after-colon:
    - 1
    - include: true
  space-after-comma:
    - 1
    - include: true
  space-before-bang:
    - 1
    - include: true
  space-before-brace:
    - 1
    - include: true
  space-before-colon: 1
  space-between-parens:
    - 1
    - include: false
  trailing-semicolon: 1
  url-quotes: 1
  hex-length:
    - 1
    - style: long
  hex-notation:
    - 1
    - style: lowercase
  indentation:
    - 1
    - size: 'tab'
  zero-unit: 1
  quotes:
    - 1
    - style: single