version: 2
general:
  branches:
    only:
      - master
jobs:
  build:
    docker:
      - image: circleci/node:9.2.1
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install npm modules
          command: yarn
      - run:
          name: Build application files
          command: yarn run build
      - run:
          name: Build application Docker image
          command: docker build -f tools/docker/prod/Dockerfile -t ryanep/portfolio .
      - run:
          name: test
          command: docker save dokku/ryanep-frontend:$(git rev-parse --short HEAD) | bzip2 | ssh root@$SERVER_IP "bunzip2 | docker load"
      - deploy:
          name: Deploy application to server
          command: ssh root@$SERVER_IP "dokku tags:create ryanep-frontend previous; dokku tags:deploy ryanep-frontend $(git rev-parse --short HEAD) && dokku tags:create ryanep-frontend latest"