version: 2
general:
  branches:
    only:
      - master
dependencies:
  cache_directories:
    - node_modules
jobs:
  test:
    docker:
      - image: circleci/node:10.15.0
    steps:
      - checkout
      - run:
          name: Install node modules
          command: yarn
      - run:
          name: Test code
          command: echo "Run tests"
      - run:
          name: Lint code
          command: yarn lint
  build:
    docker:
      - image: circleci/node:10.15.0
    steps:
      - checkout
      - run:
          name: Install node modules
          command: yarn
      - run:
          name: Test code
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - ./dist
  deploy-static:
    docker:
      - image: circleci/python:3.6.8-jessie
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to S3
          command: |
            aws s3 sync ./dist/client/ s3://cdn.ryanep.com --delete --acl public-read
  deploy:
    docker:
      - image: circleci/node:10.15.0
    steps:
      - setup_remote_docker
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build website
          command: |
            echo "[BUILDING] website"
            docker build -t dokku/ryanep-frontend:latest .
            docker save dokku/ryanep-frontend:latest -o ./ryanep-frontend.tar
            gzip ./ryanep-frontend.tar
            scp -o StrictHostKeyChecking=no ./ryanep-frontend.tar.gz ${SERVER_USER}@${SERVER_IP}:~/
            ssh -o StrictHostKeyChecking=no ${SERVER_USER}@${SERVER_IP} " \
              gunzip -f ~/ryanep-frontend.tar.gz; \
              docker load -i ~/ryanep-frontend.tar; \
              rm -f ryanep-frontend.tar; \
            "
            ssh -o StrictHostKeyChecking=no ${SERVER_USER}@${SERVER_IP} " \
              dokku tags:create ryanep-frontend previous; \
              dokku tags:deploy ryanep-frontend latest; \
              dokku tags:create ryanep-frontend latest; \
              dokku cleanup && rm ~/ryanep-frontend.tar; \
              docker image prune -a -f --filter "label=ryanep-frontend" \
            "
workflows:
  version: 2
  test_build_plan_deploy:
    jobs:
      - test
      - build
      - deploy-static:
          requires:
            - build
      - deploy:
          requires:
            - deploy-static
