version: 2
general:
  branches:
    only:
      - master
dependencies:
  cache_directories:
    - node_modules
jobs:
  build:
    docker:
      - image: circleci/node:9.0.0
    working_directory: ~/app
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Install node modules
          command: yarn
      - run:
          name: Lint code
          command: make lint
      - run:
          name: Test code
          command: make test
      - run:
          name: Build code
          command: make build
      - run:
          name: Build docker image
          command: make build-docker
      - run:
          name: Deploy docker image
          command: make deploy
